development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: list_development
  pool: 5
  username: chandana
  password: chubul
  host: localhost
  
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: list_test
  pool: 5
  username: chandana
  password: chubul
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: list_production
  pool: 5
  username: chandana
  password: chubul
  host: localhost