# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15b316a4584ac80c56974ca7b23c9f9a1e315bc88639e0f9b95152981c070fbc75890e35331870f96c9d3687cf42baaf8140860d268f2827bb6fa033eebcbc0f

test:
  secret_key_base: 68688dc43013e776e14836175d08cd26def5d3d66c1ec218cc1dda9c1239d305c380c9679d269e9d056093bef43e631c299ece46efff48f8d0d36d44efacbcd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

profiles:
  production:
    base_url: http://chandananc.github.io/list
    deploy:
      host: github_pages
      # use gh-branch for repositories other than <username>.github.io
      branch: gh-pages
      # use master branch for <username>.github.io repository
      #branch: master
